/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package cl.duoc.zoologico.gui;

import cl.duoc.zoologico.models.Animal;
import cl.duoc.zoologico.models.AnimalLeon;
import cl.duoc.zoologico.service.IZoologicoService;
import cl.duoc.zoologico.service.ZoologicoService;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mangl
 */
public class RAnimalesGUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form RAnimalesGUI
     */
    IZoologicoService servicio = AnimalGUI.servicio;
    public RAnimalesGUI() {
        initComponents();
        if(servicio == null)
            servicio =  new ZoologicoService();
        lista();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAnimales = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Reporte de animales");

        tblAnimales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAnimales);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void lista(){
        DefaultTableModel tabla = new DefaultTableModel();
        tabla.addColumn("N°Chip");
        tabla.addColumn("Nombre");
        tabla.addColumn("Edad");
        tabla.addColumn("Tipo de animal");
        tabla.addColumn("Tipo de clima donde vive");
        tabla.addColumn("Descripción");
        tblAnimales.setModel(tabla);
    
        for(Animal animal : servicio.listaAn()){
        Object[] fila = {
        animal.getChip(),
        animal.getNombre(),
        animal.getEdad(),
        animal.getTipoAnimal(),
        animal.getTipoClima(),
        animal.getDescripcion()
        };
        tabla.addRow(fila);
    }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAnimales;
    // End of variables declaration//GEN-END:variables
}
