/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cl.duoc.zoologico;

import cl.duoc.zoologico.gui.AmbienteGUI;
import cl.duoc.zoologico.gui.AnimalGUI;
import cl.duoc.zoologico.gui.ElefanteGUI;
import cl.duoc.zoologico.gui.EntradaGUI;
import cl.duoc.zoologico.gui.LeonGUI;
import cl.duoc.zoologico.gui.OrangutanGUI;
import cl.duoc.zoologico.gui.RAmbienteGUI;
import cl.duoc.zoologico.gui.RAnimalesGUI;
import cl.duoc.zoologico.gui.REntradaGUI;
import cl.duoc.zoologico.gui.RVisitanteGUI;
import cl.duoc.zoologico.gui.TigreGUI;
import cl.duoc.zoologico.gui.VisitanteGUI;
import cl.duoc.zoologico.service.IZoologicoService;
import cl.duoc.zoologico.service.ZoologicoService;

/**
 *
 * @author mangl
 */
public class Zoologico extends javax.swing.JFrame {

    /**
     * Creates new form Zoologico
     */
    public static IZoologicoService servicio;
    public Zoologico() {
        initComponents();
        if(servicio == null)
            servicio =  new ZoologicoService();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        entrada = new javax.swing.JMenuItem();
        visita = new javax.swing.JMenuItem();
        ambientes = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        nuevoAnimal = new javax.swing.JMenuItem();
        leon = new javax.swing.JMenuItem();
        tigre = new javax.swing.JMenuItem();
        elefante = new javax.swing.JMenuItem();
        orangutan = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        reporteEntrada = new javax.swing.JMenuItem();
        reporteVisitante = new javax.swing.JMenuItem();
        reportAmb = new javax.swing.JMenuItem();
        repAnimales = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 338, Short.MAX_VALUE)
        );

        jMenu2.setText("Registros y Entradas");

        entrada.setText("Pedir Entrada");
        entrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaActionPerformed(evt);
            }
        });
        jMenu2.add(entrada);

        visita.setText(" Registro de visitantes");
        visita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitaActionPerformed(evt);
            }
        });
        jMenu2.add(visita);

        ambientes.setText("Registro de ambientes");
        ambientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ambientesActionPerformed(evt);
            }
        });
        jMenu2.add(ambientes);

        jMenu1.setText("Registrar animales");

        nuevoAnimal.setText("Nuevo animal");
        nuevoAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoAnimalActionPerformed(evt);
            }
        });
        jMenu1.add(nuevoAnimal);

        leon.setText("Leon");
        leon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leonActionPerformed(evt);
            }
        });
        jMenu1.add(leon);

        tigre.setText("Tigre");
        tigre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tigreActionPerformed(evt);
            }
        });
        jMenu1.add(tigre);

        elefante.setText("Elefante");
        elefante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elefanteActionPerformed(evt);
            }
        });
        jMenu1.add(elefante);

        orangutan.setText("Orangutan");
        orangutan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orangutanActionPerformed(evt);
            }
        });
        jMenu1.add(orangutan);

        jMenu2.add(jMenu1);

        jMenuBar2.add(jMenu2);

        jMenu3.setText("Reportes");

        reporteEntrada.setText("Reporte de entradas");
        reporteEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteEntradaActionPerformed(evt);
            }
        });
        jMenu3.add(reporteEntrada);

        reporteVisitante.setText("Reporte de visitantes");
        reporteVisitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteVisitanteActionPerformed(evt);
            }
        });
        jMenu3.add(reporteVisitante);

        reportAmb.setText("Reporte de ambientes");
        reportAmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportAmbActionPerformed(evt);
            }
        });
        jMenu3.add(reportAmb);

        repAnimales.setText("Reporte de animales");
        repAnimales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repAnimalesActionPerformed(evt);
            }
        });
        jMenu3.add(repAnimales);

        jMenuBar2.add(jMenu3);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaActionPerformed
        // TODO add your handling code here:
        EntradaGUI entrada = new EntradaGUI();
        desktop.add(entrada);
        entrada.setVisible(true);
    }//GEN-LAST:event_entradaActionPerformed

    private void visitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitaActionPerformed
        // TODO add your handling code here:
        VisitanteGUI visita = new VisitanteGUI();
        desktop.add(visita);
        visita.setVisible(true);
    }//GEN-LAST:event_visitaActionPerformed

    private void ambientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ambientesActionPerformed
        // TODO add your handling code here:
        AmbienteGUI ambiente = new AmbienteGUI();
        desktop.add(ambiente);
        ambiente.setVisible(true);
    }//GEN-LAST:event_ambientesActionPerformed

    private void nuevoAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoAnimalActionPerformed
        // TODO add your handling code here:
        AnimalGUI nuevo = new AnimalGUI();
        desktop.add(nuevo);
        nuevo.setVisible(true);
    }//GEN-LAST:event_nuevoAnimalActionPerformed

    private void reporteEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteEntradaActionPerformed
        // TODO add your handling code here:
        REntradaGUI ent = new REntradaGUI();
        desktop.add(ent);
        ent.setVisible(true);
    }//GEN-LAST:event_reporteEntradaActionPerformed

    private void reporteVisitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteVisitanteActionPerformed
        // TODO add your handling code here:
        RVisitanteGUI visit = new RVisitanteGUI();
        desktop.add(visit);
        visit.setVisible(true);
    }//GEN-LAST:event_reporteVisitanteActionPerformed

    private void reportAmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportAmbActionPerformed
        // TODO add your handling code here:
        RAmbienteGUI amb = new RAmbienteGUI();
        desktop.add(amb);
        amb.setVisible(true);
    }//GEN-LAST:event_reportAmbActionPerformed

    private void leonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leonActionPerformed
        // TODO add your handling code here:
        LeonGUI n = new LeonGUI();
        desktop.add(n);
        n.setVisible(true);
    }//GEN-LAST:event_leonActionPerformed

    private void tigreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tigreActionPerformed
        // TODO add your handling code here:
        TigreGUI t = new TigreGUI();
        desktop.add(t);
        t.setVisible(true);
    }//GEN-LAST:event_tigreActionPerformed

    private void elefanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elefanteActionPerformed
        // TODO add your handling code here:
        ElefanteGUI fant = new ElefanteGUI();
        desktop.add(fant);
        fant.setVisible(true);
    }//GEN-LAST:event_elefanteActionPerformed

    private void orangutanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orangutanActionPerformed
        // TODO add your handling code here:
        OrangutanGUI orange = new OrangutanGUI();
        desktop.add(orange);
        orange.setVisible(true);
    }//GEN-LAST:event_orangutanActionPerformed

    private void repAnimalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repAnimalesActionPerformed
        // TODO add your handling code here:
        RAnimalesGUI an = new RAnimalesGUI();
        desktop.add(an);
        an.setVisible(true);
    }//GEN-LAST:event_repAnimalesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Zoologico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Zoologico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Zoologico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Zoologico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Zoologico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ambientes;
    public static javax.swing.JDesktopPane desktop;
    private javax.swing.JMenuItem elefante;
    private javax.swing.JMenuItem entrada;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem leon;
    private javax.swing.JMenuItem nuevoAnimal;
    private javax.swing.JMenuItem orangutan;
    private javax.swing.JMenuItem repAnimales;
    private javax.swing.JMenuItem reportAmb;
    private javax.swing.JMenuItem reporteEntrada;
    private javax.swing.JMenuItem reporteVisitante;
    private javax.swing.JMenuItem tigre;
    private javax.swing.JMenuItem visita;
    // End of variables declaration//GEN-END:variables
}
